# Generated by Django 2.2.8 on 2020-02-04 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20200204_2221'),
        ('accounts', '0002_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='purchase.Cart', verbose_name='سبد خرید'),
            preserve_default=False,
        ),
    ]
