language: python

python:
  - "3.6"

env:
  global:
    - COMMITTER: $(git --no-pager show -s --format=\%ae)

notifications:
  email:
    enabled: true
    on_success: always # default: change
    on_failure: always # default: always



install:
  - sudo docker-compose up -d migrate app

script:
  - echo Committer: ${COMMITTER}
  - sudo docker-compose run test
