#!/bin/bash

set -e
set -o pipefail


git -C $1 reset HEAD --hard
git -C $1 pull
docker-compose -f $1/docker-compose.yml down
docker-compose -f $1/docker-compose.yml up --exit-code-from migrate --build
#docker-compose -f $1/docker-compose.yml run migrate
#docker-compose -f $1/docker-compose.yml up -d app
