version: '3'

services:
  makemigrations:
    build: .
    command: python app/manage.py makemigrations
    volumes:
      - .:/code
      -

  migrate:
    build: .
    command: python app/manage.py migrate
    volumes:
      - .:/code

  createsuperuser:
    build: .
    command: python app/manage.py createsuperuser
    volumes:
      - .:/code
      -

  test:
    build: .
    command: python app/manage.py test app
    volumes:
      - .:/code

  app:
    build: .
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
