version: '3'

services:
  migration:
    build: .
    command: python app/manage.py migrate
    volumes:
      - .:/code

  test:
    build: .
    command: python app/manage.py test app
    volumes:
      - .:/code

  app:
    build: .
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
