version: '3'

services:
  app:
    build: .
    command: bash -c "python app/manage.py migrate && python app/manage.py test app && if [ $ISTEST -eq 0 ]; then python app/manage.py runserver 0.0.0.0:8000; else echo 'Done!'; fi"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
