version: '3'

services:
  app:
    build: .
    command: bash -c "python app/manage.py migrate && python app/manage.py test app && python app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
