# Generated by Django 2.2.8 on 2020-02-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='products.Product', verbose_name='محصول'),
        ),
    ]
