# Generated by Django 2.2.8 on 2020-02-08 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200202_1625'),
        ('accounts', '0003_buyer_cart'),
        ('purchase', '0002_auto_20200204_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product', verbose_name='محصول'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(verbose_name='مبلغ')),
                ('payment_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='زمان پرداخت')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Buyer', verbose_name='خریدار')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=2000, verbose_name='آدرس')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('delivery_date', models.DateField(verbose_name='زمان تحویل')),
                ('status', models.IntegerField(choices=[(1, 'در انتظار'), (2, 'پرداخت شده')], default=1, verbose_name='وضعیت')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Buyer', verbose_name='خریدار')),
                ('products', models.ManyToManyField(to='products.Product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
            },
        ),
    ]
