# Generated by Django 2.2.10 on 2020-02-16 19:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_charge'),
        ('purchase', '0004_auto_20200212_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product', verbose_name='محصول'),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='زمان شروع')),
                ('end_datetime', models.DateTimeField(verbose_name='زمان پایان')),
                ('sale_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='مقدار تخفیف')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Vendor', verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'کمپین',
                'verbose_name_plural': 'کمپین\u200cها',
            },
        ),
    ]
