# Generated by Django 2.2.8 on 2020-02-17 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200202_1625'),
        ('accounts', '0005_auto_20200217_0033'),
        ('purchase', '0005_auto_20200216_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ پرداخت')),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Buyer', verbose_name='خریدار')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='محصول')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Vendor', verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'پرداخت فروشنده',
                'verbose_name_plural': 'پرداخت\u200cهای فروشندگان',
            },
        ),
    ]
