# Generated by Django 2.2.8 on 2020-02-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_vendorpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_datetime',
            field=models.DateField(verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_datetime',
            field=models.DateField(verbose_name='زمان شروع'),
        ),
    ]
